name: macOS
on:
  workflow_dispatch:

jobs:
  gnat_gprbuild:
    name: GNAT macOS
    runs-on: macos-12
    steps:
    - name: Checkout Project
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install e3-core==22.1.0

    - name: Build GNAT native
      run: ./anod build gcc -v --loglevel DEBUG --enable-cleanup

    - uses: actions/upload-artifact@v2
      with:
        name: debug
        path: sbx/*
        retention-days: 30
