name: macOS_x86
on:
  workflow_dispatch:

jobs:
  gnat_gprbuild:
    name: GNAT macOS
    runs-on: macos-12
    steps:
    - name: Checkout Project
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install e3-core==22.1.0

    - name: Build GNAT native
      run: ./anod build gcc -v --loglevel DEBUG

    - name: Tar Files
      run: tar -cvf debug.tar sbx/*-darwin/gcc/*

    - uses: actions/upload-artifact@v4
      with:
        name: Upload Debug
        path: debug.tar
